### PR TITLE
Mansi Singh.md

### PR DESCRIPTION
**Pull request by Mansi-1120**
Pls add my details

### CODE REVIEW

**Comment by Mansi-1120** [comment]
Can you please accept my 3 more pull request, please brother

**Comment by tarunsinghofficial** [comment]
Please subscribe my channel and also share it.
Thanks

**Comment by Mansi-1120** [comment]
Already subscribed and Shere your channel in my college group.

**Comment by Mansi-1120** [comment]
Please brother help me to complete three more pull request, please tell me
what to do.

**Pull request merged**
